var simpleNodes =[
 	{ id:1, pId:0, name:"手机", ename:"Mobile", open:true},
 	{ id:11, pId:1, name:"诺基亚", ename:"Nokia"},
 	{ id:111, pId:11, name:"C6(音乐版)", ename:"C6(Music)"},
 	{ id:112, pId:11, name:"X6(导航版)", ename:"X6(GPS)"},
 	{ id:113, pId:11, name:"5230(世博版)", ename:"5230(SB)"},
 	{ id:114, pId:11, name:"N97mini", ename:"N97mini"},
 	{ id:12, pId:1, name:"三星", ename:"Samsung"},
 	{ id:121, pId:12, name:"I9000(联通版)", ename:"I9000(Unicom)"},
 	{ id:122, pId:12, name:"I9000(移动版)", ename:"I9000(China Mobile)"},
 	{ id:123, pId:12, name:"Galaxy Naos", ename:"Galaxy Naos"},
 	{ id:124, pId:12, name:"Fascinate", ename:"Fascinate"},
 	{ id:13, pId:1, name:"索爱", ename:"Sony Ericsson"},
 	{ id:131, pId:13, name:"U1i(Satio)", ename:"U1i(Satio)"},
 	{ id:132, pId:13, name:"U5i(Vivaz)", ename:"U5i(Vivaz)"},
 	{ id:133, pId:13, name:"X10i", ename:"X10i"},
 	{ id:134, pId:13, name:"Aino mini", ename:"Aino mini"},
 	{ id:14, pId:1, name:"多普达", ename:"Dopod"},
 	{ id:2, pId:0, name:"电脑", ename:"Computer", open:true},
 	{ id:21, pId:2, name:"硬件", ename:"Hardware"},
 	{ id:211, pId:21, name:"主板", ename:"Motherboard"},
 	{ id:212, pId:21, name:"显卡", ename:"Graphics"},
 	{ id:213, pId:21, name:"CPU", ename:"CPU"},
 	{ id:214, pId:21, name:"内存", ename:"Memory"},
 	{ id:215, pId:21, name:"硬盘", ename:"Hard disk"},
 	{ id:216, pId:21, name:"音箱", ename:"Speaker"},
 	{ id:217, pId:21, name:"机箱", ename:"Chassis"},
 	{ id:218, pId:21, name:"电源", ename:"Power supply"},
 	{ id:22, pId:2, name:"整机", ename:"Software"},
 	{ id:221, pId:22, name:"联想", ename:"Lenovo"},
 	{ id:222, pId:22, name:"戴尔", ename:"Dell"},
 	{ id:223, pId:22, name:"方正", ename:"Founder"},
 	{ id:224, pId:22, name:"宏基", ename:"Acer"},
 	{ id:225, pId:22, name:"惠普", ename:"Hewlett-Packard"},
 	{ id:23, pId:2, name:"网络设备", ename:"Network"},
 	{ id:231, pId:23, name:"网卡", ename:"NIC"},
 	{ id:232, pId:23, name:"交换机", ename:"Switch"},
 	{ id:233, pId:23, name:"路由器", ename:"Router"},
 	{ id:3, pId:0, name:"家电", ename:"Home Appliances", open:true},
 	{ id:31, pId:3, name:"冰箱", ename:"Refrigerator", isParent:true},
 	{ id:32, pId:3, name:"电视", ename:"TV"},
 	{ id:321, pId:32, name:"液晶", ename:"Liquid crystal"},
 	{ id:322, pId:32, name:"等离子", ename:"Plasma"},
 	{ id:323, pId:32, name:"3D", ename:"Three-dimensional"},
 	{ id:33, pId:3, name:"空调", ename:"Air conditioning"}
 ];